const { ROLES } = require("./roles");
const { PERMISSIONS } = require("./permissions");

const rolePermissions = Object.freeze({

    [ROLES.SUPER_ADMIN]: ["*"],

    [ROLES.BRANCH_ADMIN]: [
        PERMISSIONS.USER_VIEW,
        PERMISSIONS.USER_CREATE,
        PERMISSIONS.USER_UPDATE,
        PERMISSIONS.USER_STATUS_UPDATE,

        PERMISSIONS.BRANCH_VIEW,

        PERMISSIONS.CATEGORY_VIEW,

        PERMISSIONS.VENDOR_VIEW,
        PERMISSIONS.VENDOR_CREATE,
        PERMISSIONS.VENDOR_UPDATE,

        PERMISSIONS.INVENTORY_VIEW,
        PERMISSIONS.INVENTORY_CREATE,
        PERMISSIONS.INVENTORY_UPDATE,
        PERMISSIONS.INVENTORY_CHANGE_STATUS,

        PERMISSIONS.STOCK_MOVEMENT_VIEW,
        PERMISSIONS.STOCK_IN_CREATE,
        PERMISSIONS.STOCK_OUT_CREATE,
        PERMISSIONS.STOCK_TRANSFER_CREATE,
        PERMISSIONS.STOCK_ADJUSTMENT_CREATE,

        PERMISSIONS.PURCHASE_VIEW,
        PERMISSIONS.PURCHASE_CREATE,

        PERMISSIONS.ASSET_VIEW,
        PERMISSIONS.ASSET_CREATE,
        PERMISSIONS.ASSET_UPDATE,
        PERMISSIONS.ASSET_CHANGE_STATUS,
        PERMISSIONS.ASSET_ASSIGN,
        PERMISSIONS.ASSET_RETURN,

        PERMISSIONS.MAINTENANCE_VIEW,
        PERMISSIONS.MAINTENANCE_CREATE,
        PERMISSIONS.MAINTENANCE_ASSIGN,
        PERMISSIONS.MAINTENANCE_UPDATE_STATUS,
        PERMISSIONS.MAINTENANCE_DELETE,

        PERMISSIONS.ACTIVITY_VIEW,

        PERMISSIONS.SETTINGS_VIEW,

        PERMISSIONS.REPORT_DASHBOARD,

        PERMISSIONS.REPORT_INVENTORY,
        PERMISSIONS.REPORT_INVENTORY_EXPORT,

        PERMISSIONS.REPORT_LOW_STOCK,
        PERMISSIONS.REPORT_LOW_STOCK_EXPORT,

        PERMISSIONS.REPORT_ASSET,
        PERMISSIONS.REPORT_ASSET_EXPORT,

        PERMISSIONS.REPORT_STOCK_MOVEMENT,
        PERMISSIONS.REPORT_STOCK_MOVEMENT_EXPORT,

        PERMISSIONS.REPORT_PURCHASE,
        PERMISSIONS.REPORT_PURCHASE_EXPORT,

        PERMISSIONS.REPORT_MAINTENANCE,
        PERMISSIONS.REPORT_MAINTENANCE_EXPORT,

        PERMISSIONS.REPORT_VENDOR,
        PERMISSIONS.REPORT_VENDOR_EXPORT,
    ],

    [ROLES.INVENTORY_STAFF]: [
        PERMISSIONS.CATEGORY_VIEW,
        PERMISSIONS.VENDOR_VIEW,
        PERMISSIONS.INVENTORY_VIEW,

        PERMISSIONS.STOCK_MOVEMENT_VIEW,
        PERMISSIONS.STOCK_IN_CREATE,
        PERMISSIONS.STOCK_OUT_CREATE,

        PERMISSIONS.PURCHASE_VIEW,

        PERMISSIONS.ASSET_VIEW,
        PERMISSIONS.ASSET_CREATE,
        PERMISSIONS.ASSET_ASSIGN,
        PERMISSIONS.ASSET_RETURN,

        PERMISSIONS.MAINTENANCE_VIEW,
        PERMISSIONS.MAINTENANCE_CREATE,

        PERMISSIONS.REPORT_DASHBOARD,

        PERMISSIONS.REPORT_INVENTORY,
        PERMISSIONS.REPORT_INVENTORY_EXPORT,

        PERMISSIONS.REPORT_LOW_STOCK,
        PERMISSIONS.REPORT_LOW_STOCK_EXPORT,

        PERMISSIONS.REPORT_ASSET,
        PERMISSIONS.REPORT_ASSET_EXPORT,

        PERMISSIONS.REPORT_STOCK_MOVEMENT,
        PERMISSIONS.REPORT_STOCK_MOVEMENT_EXPORT,

        PERMISSIONS.REPORT_PURCHASE,
        PERMISSIONS.REPORT_PURCHASE_EXPORT,

        PERMISSIONS.REPORT_VENDOR,
    ],

    [ROLES.MAINTENANCE_STAFF]: [
        PERMISSIONS.CATEGORY_VIEW,
        PERMISSIONS.INVENTORY_VIEW,
        PERMISSIONS.STOCK_MOVEMENT_VIEW,
        PERMISSIONS.ASSET_VIEW,

        PERMISSIONS.MAINTENANCE_VIEW,
        PERMISSIONS.MAINTENANCE_UPDATE_STATUS,
        PERMISSIONS.MAINTENANCE_COMPLETE,

        PERMISSIONS.REPORT_DASHBOARD,
        PERMISSIONS.REPORT_ASSET,
        PERMISSIONS.REPORT_MAINTENANCE,
        PERMISSIONS.REPORT_MAINTENANCE_EXPORT,
        
    ],

    [ROLES.AUDITOR]: [
        PERMISSIONS.BRANCH_VIEW,
        PERMISSIONS.CATEGORY_VIEW,
        PERMISSIONS.VENDOR_VIEW,
        PERMISSIONS.INVENTORY_VIEW,
        PERMISSIONS.STOCK_MOVEMENT_VIEW,
        PERMISSIONS.PURCHASE_VIEW,  
        PERMISSIONS.ASSET_VIEW,
        PERMISSIONS.MAINTENANCE_VIEW,
        PERMISSIONS.ACTIVITY_VIEW,
        PERMISSIONS.SETTINGS_VIEW,
        
        PERMISSIONS.REPORT_DASHBOARD,

        PERMISSIONS.REPORT_INVENTORY,
        PERMISSIONS.REPORT_INVENTORY_EXPORT,

        PERMISSIONS.REPORT_LOW_STOCK,
        PERMISSIONS.REPORT_LOW_STOCK_EXPORT,

        PERMISSIONS.REPORT_ASSET,
        PERMISSIONS.REPORT_ASSET_EXPORT,

        PERMISSIONS.REPORT_STOCK_MOVEMENT,
        PERMISSIONS.REPORT_STOCK_MOVEMENT_EXPORT,

        PERMISSIONS.REPORT_PURCHASE,
        PERMISSIONS.REPORT_PURCHASE_EXPORT,

        PERMISSIONS.REPORT_MAINTENANCE,
        PERMISSIONS.REPORT_MAINTENANCE_EXPORT,

        PERMISSIONS.REPORT_VENDOR,
        PERMISSIONS.REPORT_VENDOR_EXPORT,
    ]
});

exports.ROLE_PERMISSIONS = rolePermissions;